-- Insert Breaking Bad characters
INSERT INTO breakingbad_trading (name, img_filename, age, gender, was_lawyer, won_emmy, family, survived) VALUES
  ('Walter White', 'white_walter.jpg', 52, 'M', FALSE, TRUE, 'White', FALSE),
  ('Jesse Pinkman', 'pinkman_jesse.jpg', 27, 'M', FALSE, TRUE, NULL, TRUE),
  ('Skyler White', 'white_skyler.jpg', 42, 'F', FALSE, TRUE, 'White', TRUE),
  ('Hank Schrader', 'schrader_hank.jpg', 46, 'M', FALSE, TRUE, 'Schrader', FALSE),
  ('Marie Schrader', 'schrader_marie.jpg', 40, 'F', FALSE, FALSE, 'Schrader', TRUE),
  ('Walter White Jr.', 'white_waltjr.jpg', 17, 'M', FALSE, FALSE, 'White', TRUE),
  ('Holly White', 'white_holly.jpg', 1, 'F', FALSE, FALSE, 'White', TRUE),
  ('Saul Goodman', 'goodman_saul.jpg', 45, 'M', TRUE, FALSE, NULL, TRUE),
  ('Mike Ehrmantraut', 'ehrmantraut_mike.jpg', 64, 'M', FALSE, TRUE, NULL, FALSE),
  ('Gustavo Fring', 'fring_gustavo.jpg', 52, 'M', FALSE, TRUE, NULL, FALSE),
  ('Hector Salamanca', 'salamanca_hector.jpg', 75, 'M', FALSE, FALSE, 'Salamanca', FALSE),
  ('Tuco Salamanca', 'salamanca_tuco.jpg', 34, 'M', FALSE, FALSE, 'Salamanca', FALSE),
  ('Lalo Salamanca', 'salamanca_lalo.jpg', 38, 'M', FALSE, FALSE, 'Salamanca', FALSE),
  ('Marco Salamanca', 'salamanca_marco.jpg', 29, 'M', FALSE, FALSE, 'Salamanca', FALSE),
  ('Leonel Salamanca', 'salamanca_leonel.jpg', 28, 'M', FALSE, FALSE, 'Salamanca', FALSE),
  ('Lydia Rodarte-Quayle', 'quayle_lydia.jpg', 38, 'F', FALSE, FALSE, NULL, FALSE),
  ('Jane Margolis', 'margolis_jane.jpg', 26, 'F', FALSE, FALSE, NULL, FALSE),
  ('Huell Babineaux', 'babineaux_huell.jpg', 43, 'M', FALSE, FALSE, NULL, TRUE),
  ('Chuck McGill', 'mcgill_chuck.jpg', 58, 'M', TRUE, TRUE, NULL, FALSE),
  ('Kim Wexler', 'wexler_kim.jpg', 35, 'F', TRUE, TRUE, NULL, TRUE),
  ('Howard Hamlin', 'hamlin_howard.jpg', 44, 'M', TRUE, FALSE, NULL, FALSE),
  ('Juan Bolsa', 'bolsa_juan.jpg', 48, 'M', FALSE, FALSE, NULL, FALSE),
  ('Don Eladio', 'eladio_don.jpg', 62, 'M', FALSE, FALSE, NULL, FALSE),
  ('Tyrus Kitt', 'tyrus.jpg', 39, 'M', FALSE, FALSE, NULL, FALSE),
  ('Victor', 'victor.jpg', 32, 'M', FALSE, FALSE, NULL, FALSE),
  ('Jack Welker', 'welker_jack.jpg', 52, 'M', FALSE, FALSE, NULL, FALSE),
  ('Stacey Ehrmantraut', 'ehrmantraut_stacey.jpg', 32, 'F', FALSE, FALSE, NULL, TRUE)
ON CONFLICT (name) DO NOTHING;
