-- Insert character drawn/not drawn markets for Breaking Bad
-- These will be dynamically sampled during gameplay, but we store the structure

-- Character Drawn Markets
INSERT INTO breakingbad_markets (market_type, character_id, count, category, text_on_screen, point) VALUES
  ('character', 1, 'drawn', NULL, 'Walter White - Drawn', NULL),
  ('character', 2, 'drawn', NULL, 'Jesse Pinkman - Drawn', NULL),
  ('character', 3, 'drawn', NULL, 'Skyler White - Drawn', NULL),
  ('character', 4, 'drawn', NULL, 'Hank Schrader - Drawn', NULL),
  ('character', 5, 'drawn', NULL, 'Marie Schrader - Drawn', NULL),
  ('character', 6, 'drawn', NULL, 'Walter White Jr. - Drawn', NULL),
  ('character', 7, 'drawn', NULL, 'Holly White - Drawn', NULL),
  ('character', 8, 'drawn', NULL, 'Saul Goodman - Drawn', NULL),
  ('character', 9, 'drawn', NULL, 'Mike Ehrmantraut - Drawn', NULL),
  ('character', 10, 'drawn', NULL, 'Gustavo Fring - Drawn', NULL),
  ('character', 11, 'drawn', NULL, 'Hector Salamanca - Drawn', NULL),
  ('character', 12, 'drawn', NULL, 'Tuco Salamanca - Drawn', NULL),
  ('character', 13, 'drawn', NULL, 'Lalo Salamanca - Drawn', NULL),
  ('character', 14, 'drawn', NULL, 'Marco Salamanca - Drawn', NULL),
  ('character', 15, 'drawn', NULL, 'Leonel Salamanca - Drawn', NULL),
  ('character', 16, 'drawn', NULL, 'Lydia Rodarte-Quayle - Drawn', NULL),
  ('character', 17, 'drawn', NULL, 'Jane Margolis - Drawn', NULL),
  ('character', 18, 'drawn', NULL, 'Huell Babineaux - Drawn', NULL),
  ('character', 19, 'drawn', NULL, 'Chuck McGill - Drawn', NULL),
  ('character', 20, 'drawn', NULL, 'Kim Wexler - Drawn', NULL),
  ('character', 21, 'drawn', NULL, 'Howard Hamlin - Drawn', NULL),
  ('character', 22, 'drawn', NULL, 'Juan Bolsa - Drawn', NULL),
  ('character', 23, 'drawn', NULL, 'Don Eladio - Drawn', NULL),
  ('character', 24, 'drawn', NULL, 'Tyrus Kitt - Drawn', NULL),
  ('character', 25, 'drawn', NULL, 'Victor - Drawn', NULL),
  ('character', 26, 'drawn', NULL, 'Jack Welker - Drawn', NULL),
  ('character', 27, 'drawn', NULL, 'Stacey Ehrmantraut - Drawn', NULL),

  -- Character Not Drawn Markets
  ('character', 1, 'not_drawn', NULL, 'Walter White - Not Drawn', NULL),
  ('character', 2, 'not_drawn', NULL, 'Jesse Pinkman - Not Drawn', NULL),
  ('character', 3, 'not_drawn', NULL, 'Skyler White - Not Drawn', NULL),
  ('character', 4, 'not_drawn', NULL, 'Hank Schrader - Not Drawn', NULL),
  ('character', 5, 'not_drawn', NULL, 'Marie Schrader - Not Drawn', NULL),
  ('character', 6, 'not_drawn', NULL, 'Walter White Jr. - Not Drawn', NULL),
  ('character', 7, 'not_drawn', NULL, 'Holly White - Not Drawn', NULL),
  ('character', 8, 'not_drawn', NULL, 'Saul Goodman - Not Drawn', NULL),
  ('character', 9, 'not_drawn', NULL, 'Mike Ehrmantraut - Not Drawn', NULL),
  ('character', 10, 'not_drawn', NULL, 'Gustavo Fring - Not Drawn', NULL),
  ('character', 11, 'not_drawn', NULL, 'Hector Salamanca - Not Drawn', NULL),
  ('character', 12, 'not_drawn', NULL, 'Tuco Salamanca - Not Drawn', NULL),
  ('character', 13, 'not_drawn', NULL, 'Lalo Salamanca - Not Drawn', NULL),
  ('character', 14, 'not_drawn', NULL, 'Marco Salamanca - Not Drawn', NULL),
  ('character', 15, 'not_drawn', NULL, 'Leonel Salamanca - Not Drawn', NULL),
  ('character', 16, 'not_drawn', NULL, 'Lydia Rodarte-Quayle - Not Drawn', NULL),
  ('character', 17, 'not_drawn', NULL, 'Jane Margolis - Not Drawn', NULL),
  ('character', 18, 'not_drawn', NULL, 'Huell Babineaux - Not Drawn', NULL),
  ('character', 19, 'not_drawn', NULL, 'Chuck McGill - Not Drawn', NULL),
  ('character', 20, 'not_drawn', NULL, 'Kim Wexler - Not Drawn', NULL),
  ('character', 21, 'not_drawn', NULL, 'Howard Hamlin - Not Drawn', NULL),
  ('character', 22, 'not_drawn', NULL, 'Juan Bolsa - Not Drawn', NULL),
  ('character', 23, 'not_drawn', NULL, 'Don Eladio - Not Drawn', NULL),
  ('character', 24, 'not_drawn', NULL, 'Tyrus Kitt - Not Drawn', NULL),
  ('character', 25, 'not_drawn', NULL, 'Victor - Not Drawn', NULL),
  ('character', 26, 'not_drawn', NULL, 'Jack Welker - Not Drawn', NULL),
  ('character', 27, 'not_drawn', NULL, 'Stacey Ehrmantraut - Not Drawn', NULL)
ON CONFLICT DO NOTHING;
